module.exports = {
  content: [
    './themes/**/layouts/**/*.html',
    './content/**/layouts/**/*.html',
    './layouts/**/*.html',
    './content/**/*.{html,md}',
  ],

  darkMode: 'class',

  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '0.75rem',
        sm: '1rem',
        lg: '1.25rem',
        xl: '1.50rem',
        '2xl': '2rem',
      },
    },

    colors: {
      transparent: 'transparent',
      currentColor: 'currentColor',
      neutral: {
        DEFAULT: 'rgb(var(--color-neutral) / <alpha-value>)',
        50: 'rgb(var(--color-neutral-50) / <alpha-value>)',
        100: 'rgb(var(--color-neutral-100) / <alpha-value>)',
        200: 'rgb(var(--color-neutral-200) / <alpha-value>)',
        300: 'rgb(var(--color-neutral-300) / <alpha-value>)',
        400: 'rgb(var(--color-neutral-400) / <alpha-value>)',
        500: 'rgb(var(--color-neutral-500) / <alpha-value>)',
        600: 'rgb(var(--color-neutral-600) / <alpha-value>)',
        700: 'rgb(var(--color-neutral-700) / <alpha-value>)',
        800: 'rgb(var(--color-neutral-800) / <alpha-value>)',
        900: 'rgb(var(--color-neutral-900) / <alpha-value>)',
        950: 'rgb(var(--color-neutral-950) / <alpha-value>)',
      },
      primary: {
        50: 'rgb(var(--color-primary-50) / <alpha-value>)',
        100: 'rgb(var(--color-primary-100) / <alpha-value>)',
        200: 'rgb(var(--color-primary-200) / <alpha-value>)',
        300: 'rgb(var(--color-primary-300) / <alpha-value>)',
        400: 'rgb(var(--color-primary-400) / <alpha-value>)',
        500: 'rgb(var(--color-primary-500) / <alpha-value>)',
        600: 'rgb(var(--color-primary-600) / <alpha-value>)',
        700: 'rgb(var(--color-primary-700) / <alpha-value>)',
        800: 'rgb(var(--color-primary-800) / <alpha-value>)',
        900: 'rgb(var(--color-primary-900) / <alpha-value>)',
        950: 'rgb(var(--color-primary-950) / <alpha-value>)',
      },
      note: {
        50: 'rgb(var(--color-note-50) / <alpha-value>)',
        100: 'rgb(var(--color-note-100) / <alpha-value>)',
        200: 'rgb(var(--color-note-200) / <alpha-value>)',
        300: 'rgb(var(--color-note-300) / <alpha-value>)',
        400: 'rgb(var(--color-note-400) / <alpha-value>)',
        500: 'rgb(var(--color-note-500) / <alpha-value>)',
        600: 'rgb(var(--color-note-600) / <alpha-value>)',
        700: 'rgb(var(--color-note-700) / <alpha-value>)',
        800: 'rgb(var(--color-note-800) / <alpha-value>)',
        900: 'rgb(var(--color-note-900) / <alpha-value>)',
        950: 'rgb(var(--color-note-950) / <alpha-value>)',
      },
      tip: {
        50: 'rgb(var(--color-tip-50) / <alpha-value>)',
        100: 'rgb(var(--color-tip-100) / <alpha-value>)',
        200: 'rgb(var(--color-tip-200) / <alpha-value>)',
        300: 'rgb(var(--color-tip-300) / <alpha-value>)',
        400: 'rgb(var(--color-tip-400) / <alpha-value>)',
        500: 'rgb(var(--color-tip-500) / <alpha-value>)',
        600: 'rgb(var(--color-tip-600) / <alpha-value>)',
        700: 'rgb(var(--color-tip-700) / <alpha-value>)',
        800: 'rgb(var(--color-tip-800) / <alpha-value>)',
        900: 'rgb(var(--color-tip-900) / <alpha-value>)',
        950: 'rgb(var(--color-tip-950) / <alpha-value>)',
      },
      warning: {
        50: 'rgb(var(--color-warning-50) / <alpha-value>)',
        100: 'rgb(var(--color-warning-100) / <alpha-value>)',
        200: 'rgb(var(--color-warning-200) / <alpha-value>)',
        300: 'rgb(var(--color-warning-300) / <alpha-value>)',
        400: 'rgb(var(--color-warning-400) / <alpha-value>)',
        500: 'rgb(var(--color-warning-500) / <alpha-value>)',
        600: 'rgb(var(--color-warning-600) / <alpha-value>)',
        700: 'rgb(var(--color-warning-700) / <alpha-value>)',
        800: 'rgb(var(--color-warning-800) / <alpha-value>)',
        900: 'rgb(var(--color-warning-900) / <alpha-value>)',
        950: 'rgb(var(--color-warning-950) / <alpha-value>)',
      },
      important: {
        50: 'rgb(var(--color-important-50) / <alpha-value>)',
        100: 'rgb(var(--color-important-100) / <alpha-value>)',
        200: 'rgb(var(--color-important-200) / <alpha-value>)',
        300: 'rgb(var(--color-important-300) / <alpha-value>)',
        400: 'rgb(var(--color-important-400) / <alpha-value>)',
        500: 'rgb(var(--color-important-500) / <alpha-value>)',
        600: 'rgb(var(--color-important-600) / <alpha-value>)',
        700: 'rgb(var(--color-important-700) / <alpha-value>)',
        800: 'rgb(var(--color-important-800) / <alpha-value>)',
        900: 'rgb(var(--color-important-900) / <alpha-value>)',
        950: 'rgb(var(--color-important-950) / <alpha-value>)',
      },
    },

    extend: {
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.red[500]'),
            '--tw-prose-headings': theme('colors.pink[900]'),
            '--tw-prose-lead': theme('colors.pink[700]'),
            '--tw-prose-links': '#af00db',
            '--tw-prose-bold': theme('colors.pink[900]'),
            '--tw-prose-counters': theme('colors.pink[600]'),
            '--tw-prose-bullets': theme('colors.pink[400]'),
            '--tw-prose-hr': theme('colors.pink[300]'),
            '--tw-prose-quotes': theme('colors.pink[900]'),
            '--tw-prose-quote-borders': theme('colors.pink[300]'),
            '--tw-prose-captions': theme('colors.pink[700]'),
            '--tw-prose-code': theme('colors.pink[900]'),
            '--tw-prose-pre-code': theme('colors.pink[100]'),
            '--tw-prose-pre-bg': theme('colors.pink[900]'),
            '--tw-prose-th-borders': theme('colors.pink[300]'),
            '--tw-prose-td-borders': theme('colors.pink[200]'),
            '--tw-prose-invert-body': theme('colors.pink'),
            '--tw-prose-invert-headings': theme('colors.white'),
            '--tw-prose-invert-lead': theme('colors.pink[300]'),
            '--tw-prose-invert-links': theme('colors.white'),
            '--tw-prose-invert-bold': theme('colors.white'),
            '--tw-prose-invert-counters': theme('colors.pink[400]'),
            '--tw-prose-invert-bullets': theme('colors.pink[600]'),
            '--tw-prose-invert-hr': theme('colors.pink[700]'),
            '--tw-prose-invert-quotes': theme('colors.pink[100]'),
            '--tw-prose-invert-quote-borders': theme('colors.pink[700]'),
            '--tw-prose-invert-captions': theme('colors.pink[400]'),
            '--tw-prose-invert-code': theme('colors.white'),
            '--tw-prose-invert-pre-code': theme('colors.pink[300]'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.pink[600]'),
            '--tw-prose-invert-td-borders': theme('colors.pink[700]'),
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
};
